### ISSUE TITLE
Bryan Jenks, What is your theme.

### ISSUE THREAD

**Issue by DaniyalAhmed-kh** [BryanJenksCommunity/FAQ#50]
### Question

What is your question?

Bryan  Jenks! I know you are very busy and have alot going on but it will be really helpful if you answer. Please briefly tell me what theme are you using and what are the snippets you have added to your Obsidian Vault. I saw your videos and your published vault and it's beautiful. I also saw your zotero video and it had some snippet which made the links small in preview. Overall, Can you tell me what are the snippets and what theme you use for your vault. Thanks, 
Regards, Daniyal Ahmed.
---

By filing a question to this repo, I promise that

-   [x] I have searched open/closed issues on this repo for my answer already

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by tallguyjenks** [comment]
All of the visual things you see in my vault are a result of my custom CSS, which i give away along with my templates in exchange for signing up to my email newsletter which you can do [[[HERE]]](https://bryanjenkstech.ck.page/d4ec0713d5)

:)
