### ISSUE TITLE
Have you tried memex? it is open sourced raindrop.io alternative

### ISSUE THREAD

**Issue by tallguyjenks** [BryanJenksCommunity/FAQ#6]
Fabulous and thanks! A quick comment on your current state-of-art workflow: have you tried [memex](https://getmemex.com/)? it is open sourced raindrop.io alternative and thought you might like that :p

_Originally posted by @liutiming in https://github.com/BryanJenksCommunity/FAQ/issues/5#issuecomment-727948145_

**Comment by tallguyjenks** [comment]
@liutiming I have not, and given that its not entirely free and i like the raindrop interface better I'm unlikely to migrate, but i will check it out :)

**Comment by tallguyjenks** [comment]
OK Woah. Looking at some of their features and the main cost being just automatic sync? this actually warrants a good thorough look, Thank you for the suggestion!

**Comment by tallguyjenks** [comment]
OMG and the template posting! https://www.notion.so/Text-Export-Templates-bb1794c15dea4e588a59b52d37ca0070

this would make it much easier to import meta data into new inputs in my Obsidian vault! That settles it, migration will occur

**Comment by liutiming** [comment]
fab. will be excited to see what is your new workflow like :)

**Comment by tallguyjenks** [comment]
@liutiming oh there will be a video on this 🤣
