### ISSUE TITLE
Can you please make available your Obsidian "structure", e.g. indexing, tagging, TOC's, etc

### ISSUE THREAD

**Issue by PaulFWatts** [BryanJenksCommunity/FAQ#8]
### Question

Can you please make available your Obsidian "structure", e.g. indexing, tagging, TOC's, etc

---

By filing a question to this repo, I promise that

-   [x] I have searched open/closed issues on this repo for my answer already

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by tallguyjenks** [comment]
Index file is [[HERE]](https://github.com/BryanJenksCommunity/FAQ/blob/master/Files/INDEX.md)
My templates are here: #4 :)

**Comment by PaulFWatts** [comment]
All very helpful and appreciated. Thanks Bryan!
