### ISSUE TITLE
Converting an HTML page from a website to a note in Obsidian

### ISSUE THREAD

**Issue by theinfiniterick** [BryanJenksCommunity/FAQ#81]
### Question

What is your question?

I would like some way to copy content from a webpage and paste into into an Obsidian note and maintain the formatting, primarily for tables of data. Is there a particular plugin for this that would be useful?

---

By filing a question to this repo, I promise that

-   [x] I have searched open/closed issues on this repo for my answer already

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by tallguyjenks** [comment]
there's a feature in the obsidian settings that allows you to paste HTML content so that you can copy content directly from a page and paste it straight into obsidian :)
